# Generated by Django 3.2.12 on 2022-03-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_doula'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_status',
            field=models.CharField(choices=[('NEW', 'New'), ('CON', 'Contacted')], default='NEW', max_length=3),
        ),
    ]
