# Generated by Django 3.2.12 on 2022-03-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
