# Generated by Django 3.2.12 on 2022-03-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contact_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_status',
            field=models.CharField(choices=[('NEW', 'New'), ('CON', 'Contacted')], default='NEW', max_length=3),
        ),
    ]
