# Generated by Django 3.2.12 on 2022-03-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_contact_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
