# Generated by Django 3.2.12 on 2022-03-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
