# Generated by Django 3.2.12 on 2022-03-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='doulaprofile',
            name='is_doula',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_doula',
            field=models.BooleanField(default=False),
        ),
    ]
