# Generated by Django 3.2.12 on 2022-03-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220307_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doulaprofile',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
