# Generated by Django 3.2.12 on 2022-03-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_doulaprofile_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='doulaprofile',
            name='certification',
            field=models.TextField(blank=True),
        ),
    ]
