# Generated by Django 3.2.12 on 2022-03-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_doulaprofile_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doulaprofile',
            name='refresh_token',
        ),
        migrations.AlterField(
            model_name='doulaprofile',
            name='image',
            field=models.ImageField(default='beef_taco.jpeg', null=True, upload_to='doula/'),
        ),
    ]
