# Generated by Django 3.2.12 on 2022-03-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doulaprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doulaprofile',
            name='calendly',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doulaprofile',
            name='certification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doulaprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doulaprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doulaprofile',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doulaprofile',
            name='started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doulaprofile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doulaprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doulaprofile',
            name='why',
            field=models.TextField(blank=True, null=True),
        ),
    ]
