# Generated by Django 3.2.12 on 2022-03-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_doulaprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doulaprofile',
            name='is_active',
            field=models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive')], default='ACT', max_length=3),
        ),
    ]
