# Generated by Django 3.2.12 on 2022-03-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_doulaprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='doulaprofile',
            name='linked',
            field=models.BooleanField(default=False),
        ),
    ]
