# Generated by Django 3.2.12 on 2022-03-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_doulaprofile_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='doulaprofile',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
