# Generated by Django 3.2.12 on 2022-03-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_doulaprofile_display_calendly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doulaprofile',
            name='display_calendly',
            field=models.BooleanField(default=False),
        ),
    ]
