# Generated by Django 3.2.12 on 2022-03-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_doulaprofile_display_calendly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doulaprofile',
            name='image',
            field=models.ImageField(default='doula/download.jpeg', upload_to='doula/'),
        ),
    ]
