# Generated by Django 3.2.12 on 2022-03-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safehands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='catagory',
            field=models.CharField(choices=[('HOW', 'how'), ('WHY', 'Why'), ('WHT', 'What')], default='HOW', max_length=3),
        ),
    ]
