# Generated by Django 3.2.12 on 2022-03-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safehands', '0002_article_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageHomeOne', models.ImageField(null=True, upload_to='doula/')),
                ('imageHomeTwo', models.ImageField(null=True, upload_to='doula/')),
                ('imageHomeThree', models.ImageField(null=True, upload_to='doula/')),
                ('imageHomeFour', models.ImageField(null=True, upload_to='doula/')),
                ('imageHomeFive', models.ImageField(null=True, upload_to='doula/')),
                ('banner', models.ImageField(null=True, upload_to='doula/')),
                ('logo', models.ImageField(null=True, upload_to='doula/')),
            ],
        ),
    ]
